---
abstract: C implementation of GIS::Distance formulas.
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.69
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: GIS-Distance-Fast
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 1.22
requires:
  GIS::Distance: 0.02
  Inline: 0.44
  Inline::C: 0
  Inline::Files: 0.62
  perl: 5.8.3
version: 0.02
